version: "3"
services:
        web:
                build: .
                ports:
                        - "8000:8000"
                volumes:
                        - ./src/:/srv/prog3-2019/src
